name: ShichiZip

include:
  - project/specs/base.yml
  - project/specs/apps.yml
  - project/specs/quick-actions.yml
  - project/specs/quicklook-preview.yml
  - project/specs/schemes.yml
  - path: project/specs/unsigned.yml
    enable: ${SHICHIZIP_UNSIGNED}
